apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tasksetcontroller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tasksetcontroller
  namespace: kube-system
spec:
  serviceName: tasksetcontroller
  selector:
    matchLabels:
      app: tasksetcontroller
  replicas: 1
  template:
    metadata:
      labels:
        app: tasksetcontroller
    spec:
      containers:
        - name: tasksetcontroller
          image: 192.168.202.74:5000/openi/tasksetcontroller:v0.0.2
          imagePullPolicy: IfNotPresent